### PR TITLE
Issue #39 Ajax form is not submitting the select tag values

### PR DESCRIPTION
**Pull request by jonataa**
I've fixed the problem of issue #39.

### CODE REVIEW

**Comment by rnicholus** [comment]
Good catch!  This is likely a regression that occurred as a result of some refactoring.  Before I merge this in, I'll want to add a unit test case.  I hope to have some time to get to that this week.

**Comment by jonataa** [comment]
I've updated the unit test case as well in this commit 7b13fd8830f733933a065a5df1a622c718c2c108, I hope that help.

**Comment by rnicholus** [comment]
Are you sure that will pass?  It seems like it shouldn't, since there are no selected options.  Also, the value should be a string and not an array (representing the selected option).

**Comment by jonataa** [comment]
OMG! You're right, I'll try to improve it.

**Comment by rnicholus** [comment]
You should be able to run the tests locally by following the guide in the readme.

**Pull request merged**
